[colors.bright]
black = "#766e6b"
blue = "#407ee7"
cyan = "#00ad9c"
green = "#5ab738"
magenta = "#6666ea"
red = "#f22c40"
white = "#f1efee"
yellow = "#d5911a"

[colors.normal]
black = "#1b1918"
blue = "#407ee7"
cyan = "#00ad9c"
green = "#5ab738"
magenta = "#6666ea"
red = "#f22c40"
white = "#a8a19f"
yellow = "#d5911a"

[colors.primary]
background = "#000000"
foreground = "#eee4e1"

[cursor]
style = "Beam"

[font]
size = 11

[font.bold]
family = "Inconsolata"
style = "Regular"

[font.bold_italic]
family = "Inconsolata"
style = "Regular"

[font.italic]
family = "Inconsolata"
style = "Regular"

[font.normal]
family = "Inconsolata"
style = "Regular"

[scrolling]
history = 100000

[window]
opacity = 0.8
